// flow-typed signature: 5d10fe51603a29f4af0638edce14ec2b
// flow-typed version: <<STUB>>/commonmark_v^0.27.0/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'commonmark'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'commonmark' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'commonmark/dist/commonmark' {
  declare module.exports: any;
}

declare module 'commonmark/dist/commonmark.min' {
  declare module.exports: any;
}

declare module 'commonmark/lib/blocks' {
  declare module.exports: any;
}

declare module 'commonmark/lib/common' {
  declare module.exports: any;
}

declare module 'commonmark/lib/from-code-point' {
  declare module.exports: any;
}

declare module 'commonmark/lib/html' {
  declare module.exports: any;
}

declare module 'commonmark/lib/index' {
  declare module.exports: any;
}

declare module 'commonmark/lib/inlines' {
  declare module.exports: any;
}

declare module 'commonmark/lib/node' {
  declare module.exports: any;
}

declare module 'commonmark/lib/normalize-reference' {
  declare module.exports: any;
}

declare module 'commonmark/lib/render/html' {
  declare module.exports: any;
}

declare module 'commonmark/lib/render/renderer' {
  declare module.exports: any;
}

declare module 'commonmark/lib/xml' {
  declare module.exports: any;
}

// Filename aliases
declare module 'commonmark/dist/commonmark.js' {
  declare module.exports: $Exports<'commonmark/dist/commonmark'>;
}
declare module 'commonmark/dist/commonmark.min.js' {
  declare module.exports: $Exports<'commonmark/dist/commonmark.min'>;
}
declare module 'commonmark/lib/blocks.js' {
  declare module.exports: $Exports<'commonmark/lib/blocks'>;
}
declare module 'commonmark/lib/common.js' {
  declare module.exports: $Exports<'commonmark/lib/common'>;
}
declare module 'commonmark/lib/from-code-point.js' {
  declare module.exports: $Exports<'commonmark/lib/from-code-point'>;
}
declare module 'commonmark/lib/html.js' {
  declare module.exports: $Exports<'commonmark/lib/html'>;
}
declare module 'commonmark/lib/index.js' {
  declare module.exports: $Exports<'commonmark/lib/index'>;
}
declare module 'commonmark/lib/inlines.js' {
  declare module.exports: $Exports<'commonmark/lib/inlines'>;
}
declare module 'commonmark/lib/node.js' {
  declare module.exports: $Exports<'commonmark/lib/node'>;
}
declare module 'commonmark/lib/normalize-reference.js' {
  declare module.exports: $Exports<'commonmark/lib/normalize-reference'>;
}
declare module 'commonmark/lib/render/html.js' {
  declare module.exports: $Exports<'commonmark/lib/render/html'>;
}
declare module 'commonmark/lib/render/renderer.js' {
  declare module.exports: $Exports<'commonmark/lib/render/renderer'>;
}
declare module 'commonmark/lib/xml.js' {
  declare module.exports: $Exports<'commonmark/lib/xml'>;
}
